run:
	./modif_txt metro.txt ligne_man.txt coordonnees.txt 328
	./modif_txt metro.txt_m ligne_man.txt_m coordonnees.txt_m 280
	./modif_txt metro.txt_m_m ligne_man.txt_m_m coordonnees.txt_m_m 184
	./modif_txt metro.txt_m_m_m ligne_man.txt_m_m_m coordonnees.txt_m_m_m 153
	./modif_txt metro.txt_m_m_m_m ligne_man.txt_m_m_m_m coordonnees.txt_m_m_m_m 145
	./modif_txt metro.txt_m_m_m_m_m ligne_man.txt_m_m_m_m_m coordonnees.txt_m_m_m_m_m 36
	./modif_txt metro.txt_m_m_m_m_m_m ligne_man.txt_m_m_m_m_m_m coordonnees.txt_m_m_m_m_m_m 34
